import { useState } from "react";
import { ArrowRight, CheckCircle2, ChevronDown, ChevronUp, ShieldCheck, TrendingUp, Wallet } from "lucide-react";
import heroImage from "../assets/images/hero2.png";
import assetplusLogo from "../assets/images/Assetplus.jpeg";
import policybazaarLogo from "../assets/images/policybazaar.jpg";
import voltLogo from "../assets/images/volt.png";
import andromedaLogo from "../assets/images/andromeda.jpg";
import ruloansLogo from "../assets/images/ruloans.jpg";

const solutions = [
  { title: "Investments", text: "Grow your wealth with tailored mutual funds, stocks, and fixed deposit strategies designed for your risk profile.", Icon: TrendingUp, tone: "bg-blue-50 text-blue-600", line: "bg-blue-500" },
  { title: "Insurance", text: "Protect your family's future and your health with comprehensive, customized insurance policies.", Icon: ShieldCheck, tone: "bg-violet-50 text-violet-600", line: "bg-violet-500" },
  { title: "Loans", text: "Achieve your dreams with hassle-free personal loans, business loans, and loans against mutual funds.", Icon: Wallet, tone: "bg-emerald-50 text-emerald-600", line: "bg-emerald-500" },
];
const faqs = [
  ["What financial services does Prime Wealth offer?", "We offer mutual fund investments, life and health insurance, and loan products including home loans, business loans, and loans against mutual funds."],
  ["Is my investment safe with Prime Wealth?", "We work with SEBI-registered platforms and industry-leading institutions. Investments are routed through authorized channels for transparency and security."],
  ["How do I start investing or apply for a loan?", "Request a free consultation. We will understand your goals and guide you through the process step by step."],
  ["Are there any hidden charges for consultation?", "No. Our initial financial consultation is completely free, so you can make informed decisions with clarity."],
];

function Home() {
  const [openFaq, setOpenFaq] = useState(null);
  return <main className="overflow-hidden bg-[#f8fafc]">
    <section className="relative isolate px-4 pb-12 pt-14 sm:px-6 sm:pt-20 lg:px-8 lg:pb-20"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[32rem] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-100 via-blue-50/30 to-transparent" />
      <div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.03fr_0.97fr] lg:gap-14"><div className="max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3.5 py-2 text-xs font-extrabold tracking-[.14em] text-blue-700 uppercase shadow-sm"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Your financial partner</p><h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Your vision. <span className="text-blue-600">Our strategy.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">We simplify financial decisions for individuals and families across India — from investments and insurance to seamless loan approvals.</p>
        <div className="mt-6 grid gap-2 text-sm font-bold text-slate-700 sm:grid-cols-2">{["SEBI Registered Partners", "Tailored Financial Planning", "100% Secure Process", "Dedicated Wealth Advisors"].map((item) => <span key={item} className="flex items-center gap-2"><CheckCircle2 size={18} className="text-emerald-500" />{item}</span>)}</div>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 font-extrabold text-white shadow-lg shadow-slate-900/15 transition hover:bg-blue-700">Start your journey <ArrowRight size={18} /></a><a href="/services" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3 font-extrabold text-slate-800 transition hover:border-blue-200 hover:text-blue-700">Explore services</a></div>
        <div className="mt-9 grid grid-cols-3 divide-x divide-slate-200 rounded-2xl border border-slate-200 bg-white/70 p-4 text-center shadow-sm"><div><strong className="block text-lg text-slate-950">10M+</strong><span className="text-xs font-semibold text-slate-500">Happy families</span></div><div><strong className="block text-lg text-blue-600">50+</strong><span className="text-xs font-semibold text-slate-500">Partners</span></div><div><strong className="block text-lg text-emerald-600">₹500Cr+</strong><span className="text-xs font-semibold text-slate-500">Wealth managed</span></div></div>
      </div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 -z-10 rounded-[2.5rem] bg-blue-600/15 blur-2xl" /><img src={heroImage} alt="Family securing their financial future" className="aspect-[4/3] w-full rounded-3xl object-cover shadow-2xl shadow-blue-950/15" /><div className="absolute -bottom-4 left-4 rounded-2xl border border-white/70 bg-white/90 px-4 py-3 shadow-lg backdrop-blur"><p className="text-xs font-bold text-slate-500">Guidance built around you</p><p className="mt-0.5 text-sm font-extrabold text-slate-950">Secure. Transparent. Personal.</p></div></div></div>
    </section>
    <section className="border-y border-slate-200 bg-white px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-center text-[11px] font-extrabold tracking-[.16em] text-slate-400 uppercase">Trusted by & partnered with</p><div className="mt-6 flex flex-wrap items-center justify-center gap-x-9 gap-y-5 grayscale opacity-70"><img src={assetplusLogo} alt="AssetPlus" className="h-7 object-contain sm:h-8" /><img src={policybazaarLogo} alt="Policybazaar" className="h-7 object-contain sm:h-8" /><img src={voltLogo} alt="Volt Money" className="h-7 object-contain sm:h-8" /><img src={andromedaLogo} alt="Andromeda" className="h-7 object-contain sm:h-8" /><img src={ruloansLogo} alt="Ruloans" className="h-7 object-contain sm:h-8" /></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-xs font-extrabold tracking-[.16em] text-blue-700 uppercase">Our core solutions</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Build, protect and access your wealth.</h2><p className="mt-3 text-slate-600">Comprehensive financial services designed around your goals.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{solutions.map(({ title, text, Icon, tone, line }) => <article key={title} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className={`absolute inset-x-0 top-0 h-1 ${line}`} /><span className={`grid h-12 w-12 place-items-center rounded-xl ${tone}`}><Icon size={24} /></span><h3 className="mt-5 text-xl font-extrabold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><a href="/services" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-blue-700">Learn more <ArrowRight size={16} /></a></article>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-8 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-16"><div><p className="text-xs font-extrabold tracking-[.16em] text-blue-700 uppercase">FAQs</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Straight answers, before you start.</h2><p className="mt-4 leading-7 text-slate-600">If you have a more specific question, our advisers are a call away.</p><a href="/contact" className="mt-6 inline-flex items-center gap-2 font-extrabold text-blue-700">Talk to an adviser <ArrowRight size={17} /></a></div><div className="grid gap-3">{faqs.map(([question, answer], index) => <div key={question} className="rounded-2xl border border-slate-200 bg-white"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left text-sm font-extrabold text-slate-900 sm:text-base"><span>{question}</span>{openFaq === index ? <ChevronUp className="shrink-0 text-blue-600" /> : <ChevronDown className="shrink-0 text-slate-400" />}</button>{openFaq === index && <p className="border-t border-slate-100 px-5 py-4 text-sm leading-6 text-slate-600">{answer}</p>}</div>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 pb-14 pt-8 sm:px-6 lg:px-8 lg:pb-20"><div className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-blue-600/30 blur-3xl" /><div className="relative max-w-2xl"><p className="text-xs font-extrabold tracking-[.16em] text-blue-200 uppercase">Free consultation</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Ready to take control of your finances?</h2><p className="mt-3 text-slate-300">Start your journey towards financial freedom with a clear plan.</p></div><a href="/contact" className="relative mt-6 inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-extrabold text-slate-950 transition hover:bg-blue-50 lg:mt-0">Request consultation <ArrowRight size={18} /></a></div></section>
  </main>;
}
export default Home;
