import { Award, BarChart3, Building2, CheckCircle2, ShieldCheck, Users } from "lucide-react";
import assetplusLogo from "../assets/images/Assetplus.jpeg";
import policybazaarLogo from "../assets/images/policybazaar.jpg";
import voltLogo from "../assets/images/volt.png";
import andromedaLogo from "../assets/images/andromeda.jpg";
import ruloansLogo from "../assets/images/ruloans.jpg";

const partners = [
  ["AssetPlus", assetplusLogo, "Empowering investors with intelligent investment solutions and advisory services."],
  ["Policybazaar", policybazaarLogo, "India's leading platform for insurance and financial product comparison."],
  ["Volt Money", voltLogo, "Digital lending and financial services platform for a smarter tomorrow."],
  ["Andromeda", andromedaLogo, "Technology-driven financial solutions for businesses and individuals."],
  ["Ruloans", ruloansLogo, "Business loans and credit solutions tailored to your needs."],
];
const metrics = [["50+", "Trusted partners", Users], ["100+", "Integrated solutions", Building2], ["10M+", "Happy customers", ShieldCheck], ["7+", "Years of collaboration", Award]];

function Partners() {
  return <main className="overflow-hidden bg-[#f8fafc] px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><section className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="inline-flex rounded-full border border-blue-100 bg-white px-3.5 py-2 text-xs font-extrabold tracking-[.14em] text-blue-700 uppercase">Our partners</p><h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl">Stronger partnerships, <span className="text-blue-600">smarter finance.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">We collaborate with leading financial institutions and innovative companies to deliver reliable, seamless, and future-ready solutions.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[[ShieldCheck, "Trusted", "Partnerships", "text-blue-600 bg-blue-50"], [Award, "Secure &", "Compliant", "text-emerald-600 bg-emerald-50"], [BarChart3, "Customer", "First approach", "text-violet-600 bg-violet-50"]].map(([Icon, lineOne, lineTwo, tone]) => <div key={lineTwo} className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={20} /></span><p className="text-xs font-extrabold text-slate-700">{lineOne}<br />{lineTwo}</p></div>)}</div></div><div className="relative mx-auto grid aspect-square w-full max-w-sm place-items-center"><div className="absolute inset-3 rounded-full border border-dashed border-blue-200" /><div className="absolute inset-12 rounded-full border border-blue-100" /><div className="grid h-28 w-28 place-items-center rounded-full border-8 border-white bg-slate-950 text-3xl font-extrabold text-white shadow-xl">PW</div>{["AssetPlus", "Policybazaar", "Volt", "Ruloans"].map((name, index) => <span key={name} className={`absolute rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-extrabold text-slate-700 shadow-sm ${["top-5 left-1/2 -translate-x-1/2", "right-0 top-1/2 -translate-y-1/2", "bottom-5 left-1/2 -translate-x-1/2", "left-0 top-1/2 -translate-y-1/2"][index]}`}>{name}</span>)}</div></section>
    <section className="mx-auto mt-16 max-w-7xl lg:mt-20"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold tracking-[.16em] text-blue-700 uppercase">Our network</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Built with trusted names.</h2></div><p className="max-w-md text-sm leading-6 text-slate-600">A growing network that makes better financial products more accessible.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{partners.map(([name, logo, description]) => <article key={name} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="grid h-16 place-items-start"><img src={logo} alt={name} className="h-12 max-w-36 object-contain object-left" /></div><h3 className="mt-5 font-extrabold text-slate-950">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-blue-700"><CheckCircle2 size={15} /> Trusted network</span></article>)}</div></section>
    <section className="mx-auto mt-12 max-w-7xl rounded-3xl bg-slate-950 p-6 text-white shadow-2xl sm:p-9"><div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([number, label, Icon]) => <div key={label} className="text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-white/10 text-blue-300"><Icon size={21} /></span><strong className="mt-4 block text-3xl">{number}</strong><p className="mt-1 text-sm font-bold text-slate-200">{label}</p></div>)}</div></section>
  </main>;
}
export default Partners;
