import { ArrowRight, Check, Landmark, ShieldCheck, TrendingUp } from "lucide-react";

const services = [
  { title: "Investment", intro: "Grow your wealth with smart, structured, and goal-oriented investment solutions.", items: ["Mutual Funds", "SIP Investment", "Goal Based Planning", "Lump Sum Investment"], Icon: TrendingUp, tone: "text-blue-600 bg-blue-50", border: "border-t-blue-500" },
  { title: "Insurance", intro: "Protect what matters most with the right coverage for you and your family.", items: ["Life Insurance", "Health Insurance", "Vehicle Insurance", "Term Insurance"], Icon: ShieldCheck, tone: "text-violet-600 bg-violet-50", border: "border-t-violet-500" },
  { title: "Loans", intro: "Get the right loan for your personal or business needs with flexible terms.", items: ["Personal Loan", "Home Loan", "Business Loan", "Loan Against Mutual Funds"], Icon: Landmark, tone: "text-amber-600 bg-amber-50", border: "border-t-amber-500" },
];

function Services() {
  return <main className="overflow-hidden bg-slate-50"><section className="relative overflow-hidden bg-slate-950 px-4 py-14 text-white sm:px-6 sm:py-20 lg:px-8"><div className="pointer-events-none absolute -left-28 -top-28 h-96 w-96 rounded-full bg-blue-500/25 blur-3xl" /><div className="pointer-events-none absolute -bottom-36 right-0 h-96 w-96 rounded-full bg-violet-500/20 blur-3xl" /><div className="relative mx-auto max-w-7xl"><p className="text-xs font-extrabold tracking-[.16em] text-blue-300 uppercase">Prime Wealth solutions</p><h1 className="mt-4 max-w-3xl text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">Solutions for every <span className="text-blue-400">financial goal.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Simple. Smart. Secure. Explore comprehensive services built to help you grow, protect, and achieve more.</p><div className="mt-8 flex flex-wrap gap-3">{["Trusted clients", "Expert guidance", "Secure & transparent"].map((item) => <span key={item} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-sm font-semibold text-slate-200"><Check size={15} className="text-emerald-400" />{item}</span>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-extrabold tracking-[.16em] text-blue-700 uppercase">Our services</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Three ways we support your journey.</h2><p className="mt-3 text-slate-600">Choose the solution that best fits your financial needs today.</p></div><div className="mt-9 grid gap-5 lg:grid-cols-3">{services.map(({ title, intro, items, Icon, tone, border }) => <article key={title} className={`rounded-3xl border border-slate-200 border-t-4 ${border} bg-white p-6 shadow-sm sm:p-7`}><span className={`grid h-12 w-12 place-items-center rounded-xl ${tone}`}><Icon size={24} /></span><h3 className="mt-5 text-2xl font-extrabold text-slate-950">{title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">{intro}</p><ul className="mt-6 grid gap-3 border-t border-slate-100 pt-5">{items.map((item) => <li key={item} className="flex items-center gap-3 text-sm font-bold text-slate-700"><span className={`grid h-6 w-6 place-items-center rounded-full ${tone}`}><Check size={14} /></span>{item}</li>)}</ul></article>)}</div>
      <div className="mt-12 flex flex-col gap-6 rounded-3xl bg-blue-700 p-6 text-white shadow-xl shadow-blue-700/20 sm:p-8 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-extrabold tracking-[.16em] text-blue-100 uppercase">Free consultation</p><h2 className="mt-2 text-2xl font-extrabold">Let’s build your financial future.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Our experts are here to help you take the next step towards your goals with premium guidance.</p></div><a href="/contact" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-extrabold text-blue-800 transition hover:bg-blue-50">Talk to an expert <ArrowRight size={18} /></a></div></section>
  </main>;
}
export default Services;
